### ISSUE TITLE
Problem description and example in readme appear to be incorrect

### ISSUE THREAD

**Issue by stevenrhart** [dwave-examples/maximum-cut#8]
The problem description in the readme (including the images) seems to be describing a partitioning problem rather than a maximum cut problem. Specifically, the description and images imply that the graph must be divided into two subsets of nodes such that all nodes within each subset maintain a connection to all other nodes in the same subset. In other words, two nodes in the same subset cannot be linked by a cut edge.

I believe the description should be updated to indicate the following (although not sure of the clearest way to word this):

1. The objective is to maximize the number of edges between subsets
2. Nodes within a subset do not need to be connected to one another

In addition, the images should be updated to reflect a different set of solutions. For the example given, the best solutions would be to divide the graph into one of the following, both having a total of 5 cut edges.

1. ([2, 3], [0, 1, 4])
2. ([1, 4], [0, 2, 3])

For what it's worth, the existing implementation of the code renders the two results above as the best solutions. Please don't hesitate to reach out with questions and happy to help in any way I can.

**Comment by vgoliber** [comment]
I think it's important to note that the description and example are not incorrect, it's simply stating the problem without the additional clarification.  It's important not to read more into the problem than what's stated: it is not stated anywhere in the problem description that the two sets must be connected internally or that this is a partitioning problem (which it is a type of).  The only requirement is that we are maximizing the number of edges between the two subsets - there is no additional constraint that constrains internal set edges. Note that this is also the case for graph partitioning - there are no constraints on internal set edges, and they may also be disconnected.

**Comment by stevenrhart** [comment]
Your comments above make sense to me regarding the description. I think the updated image looks good and will be helpful in illustrating the example. Closing this issue as resolved based on your commit.
